# Generated by Django 3.1.6 on 2021-02-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='top_chart',
            new_name='bestseller',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='top_seller',
            new_name='topseller',
        ),
    ]
