# Generated by Django 3.1.6 on 2021-02-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210211_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
