# Generated by Django 3.1.6 on 2021-02-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_slider_slider2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider',
            new_name='slide',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider2',
            new_name='slide2',
        ),
    ]
