# Generated by Django 3.1.6 on 2021-03-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210223_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='minnumber',
            new_name='minquantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_instock',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
