# Generated by Django 3.1.6 on 2021-02-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210208_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
