# Generated by Django 3.1.6 on 2021-02-08 09:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210208_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='refrences',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
