# Generated by Django 3.1.6 on 2021-02-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210208_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpemail',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtppassword',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpport',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpserver',
        ),
        migrations.AlterField(
            model_name='setting',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
