# Generated by Django 3.1.6 on 2021-02-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210208_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='Phone',
            new_name='phone',
        ),
    ]
