# Generated by Django 3.1.6 on 2021-02-11 12:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
