# Generated by Django 3.1.6 on 2021-02-11 12:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210211_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider2',
        ),
        migrations.AddField(
            model_name='setting',
            name='slider',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='slider2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
