# Generated by Django 3.1.6 on 2021-02-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210211_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
