# Generated by Django 3.1.6 on 2021-02-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_slider_slider2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='slider2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider2',
        ),
    ]
