# Generated by Django 3.1.6 on 2021-02-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210211_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slides',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
