# Generated by Django 3.1.6 on 2021-02-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_slider_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
