# Generated by Django 3.1.6 on 2021-02-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210214_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='defaultpic.jpg', null=True, upload_to='images/users/'),
        ),
    ]
